version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "ci"

  # Maintain Gradle dependencies
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "gradle"
